# -*- coding: utf-8 -*-
"""NIYITEGEKA Isaie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqK344NytOfQ7SmSUH431OhFKYt6OVo1
"""

!pip install cryptography
from cryptography.fernet import Fernet

# Generate key
key=Fernet.generate_key()
cipher_suite= Fernet(key)

# message to generate

message = b"first_name: NIYITEGEKA Isaie 2401000694"

# Encrepty

encrypted_message = cipher_suite.encrypt(message)
print("Encrypted message:",encrypted_message)

# decrepted
decrypted_message = cipher_suite.decrypt(encrypted_message)
print(decrypted_message.decode())

